# Generated by Django 4.0.2 on 2022-02-23 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issusedbook',
            new_name='Issuedbook',
        ),
    ]
